### ISSUE TITLE
Feedback da comunidade

### ISSUE THREAD

**Issue by oPorks** [pagarme/papeis#1]
Meu amigo Marcelo, da Lambda3 deu um [feedback](https://www.linkedin.com/feed/update/urn:li:activity:6313536487522656256) interessante.

"Nao é chefe, mas promove, contrata e demite? Prefiro quando o time tem esse empoderamento. Isso tem funcionado bastante pra gente."

Discutimos isso entre nós e sabemos que no nosso contexto faz sentido, mas o que é Chefe? A descrição parece incongruente.

A ideia é delegarmos isso para os times, e o trabalho do Facilitador é empoderar o time para tomar essa decisão, hoje se medíssemos no Delegation Board um geral seria Sell para Demissão, Agree para Contratação e Tell para promoção.

Acreditamos que uma cultura de feedback melhora muito isso. É onde estamos trabalhando com mais esforço.

**Comment by marcusflavius** [comment]
@oporks esse tema é polêmico msm... durante a construção do papel, esse foi um dos raros pontos em que nosso time não chegou a consenso. Fato é que hoje estamos iniciando uma longa jornada de desenvolvimento dos times que facilitamos a caminho da autonomia e auto-festão. Só que nesse momento, como você bem colocou em seu comentário, nos parece necessário dar essa #gestada.

Uma vez que não escrevemos na pedra, muito menos com sangue, esse nosso manifesto, talvez possamos voltar a discutir esses dois pontos, com o objetivo de estressar mais o tema e encontrar uma forma melhor de fazer e declarar como, dentro do nosso contexto, abordaremos o "sacrifício" de #gestar, enquanto facilitamos o amadurecimento dos times.
(para que, no futuro, esse "sacrifício" seja 100% abolido das responsas do facilitador)

Ao Marcelo, muito obrigado pela contribuição na reflexão.
